---
name: Qwackify
version: dev
slug: qwackify
description: Full media control by voice! Python Baked with Caddy for reverse proxy.
url: "https://github.com/einschmidt/addon-caddy-2"
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
startup: services
map:
  - "share:rw"
  - config
  - "ssl:rw"
host_network: true
options:
  addon:
    addonport: 9413
  duckdns:
    authkey: yourauthkey
    domain: mydomain.duckdns.org
  homeassistant: 
    homeassistant: localhost
    port: 8123
    longlivedaccesstoken: accesstoken
  media: 
    movies: /media/movies
    tv: /media/tv
  args: []
  env_vars: []
  log_level: info
schema:
 # non_caddyfile_config:
  #  email: email?
  #  domain: str?
  #  destination: str?
   # port: port?
  caddy_upgrade: bool?
  caddy_fmt: bool?
  config_path: str?
  assist_language: list(en|sv)
  args:
    - str
  env_vars:
    - name: str
      value: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
environment:
  LOG_FORMAT: "{LEVEL}: {MESSAGE}"
init: false
