# Example Automation
# In combination with the intent_script, this will create alarms that sends the event timer.finished on specified time.

alias: wake_up_alarm
description: "timer.wakeup"
trigger:
  - platform: time
    at: input_datetime.wakeupalarm
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wakeup    
action:
  - service: media_player.volume_set
    data:
      volume_level: 1
    target:
      entity_id: media_player.ha
  - service: timer.start
    data: {}
    target:
      entity_id: timer.wakeup
  - service: media_player.play_media
    data:
      media_content_id: /local/sound/wakeup.mp3
      media_content_type: music
    target:
      entity_id: media_player.ha
